version: 2

build:
  os: ubuntu-22.04
  # image: latest
  tools:
    python: "3.11"

python:
  # version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

formats: []
